# class ID_Table:
#     table_name = "GEO_ID"
#     data_types_all = "string"   #set to false if table contains different data types, and assign
#                                 #   var1, var2, ..., varn data types type1, type2, ..., typen
#     var1 = "Id"#"GEO.id"
#     var2 = "Id2"#"GEO.id2"
#     var3 = "Geography"#"GEO.display-label"
#
# class Median_Age_Sex_Table:
#     table_name = "Age Brackets"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total"
#     var2 = "Under 5 years"
#     var3 = "5 to 9 years"
#     var4 = "10 to 14 years"
#     var5 = "15 to 17 years"
#     var6 = "18 and 19 years"
#     var7 = "20 years"
#     var8 = "21 years"
#     var9 = "22 to 24 years"
#     var10 = "25 to 29 years"
#     var11 = "30 to 34 years"
#     var12 = "35 to 39 years"
#     var13 = "40 to 44 years"
#     var14 = "45 to 49 years"
#     var15 = "50 to 54 years"
#     var16 = "55 to 59 years"
#     var17 = "60 and 61 years"
#     var18 = "62 to 64 years"
#     var19 = "65 and 66 years"
#     var20 = "67 to 69 years"
#     var21 = "70 to 74 years"
#     var22 = "75 to 79 years"
#     var23 = "80 to 84 years"
#     var24 = "85 years and over"
#     var25 = "Total"
#     var26 = "Under 5"
#     var27 = "5 to 17"
#     var28 = "18 to 24 years"
#     var29 = "25 to 39 years"
#     var30 = "40 to 64 years"
#     var31 = "65 years and over"
#     var32 = "75 years and over"
#     var33 = "85 years and over"
#
# class Race_Table:
#     table_name = "Race"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total population"
#     var2 = "White alone"
#     var3 = "Black or African American alone"
#     var4 = "American Indian and Alaska Native alone"
#     var5 = "Asian alone"
#     var6 = "Native Hawaiian and Other Pacific Islander alone"
#     var7 = "Some other race alone"
#     var8 = "Two or more races"
#
# class Hispanic_Origin_Table:
#     table_name = "Hispanic or Latino Origin"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total population"
#     var2 = "Not Hispanic or Latino"
#     var3 = "Hispanic or Latino"
#
# class Relationship_Children_Table:
#     table_name = "Relationship to Householder for Children Under 18 years in households"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Estimate; Total:"
#     var2 = "Estimate; Own child: - Biological child"
#     var3 = "Estimate; Own child: - Adopted child"
#     var4 = "Estimate; Own child: - Stepchild"
#     var5 = "Estimated; Grandchild"
#     var6 = "Estimate; Other relatives"
#     var7 = "Estimate; Foster child or other unrelated child"
#
# class Houshold_Relationship_Table:
#     table_name = "Household Type (including living alone) by relationship"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total Population"
#     var2 = "In households"
#     var3 = "In group quarters"
#     var4 = "Householder"
#     var5 = "Male householder (in family and nonfamily households)"
#     var6 = "Female householder (in family and nonfamily households)"
#     var7 = "In Households"
#     var8 = "Householder"
#     var9 = "Spouse"
#     var10 = "Child"
#     var11 = "Grandchild"
#     var12 = "Brother or sister"
#     var13 = "Parent"
#     var14 = "Parent-in-law"
#     var15 = "Son-in-law or daughter-in-law"
#     var16 = "Other relatives"
#     var17 = "Roomer or boarder"
#     var18 = "Housemate or roommate"
#     var19 = "Unmarried partner"
#     var20 = "Foster child"
#     var21 = "Other nonrelatives"
#     var22 = "In Households"
#     var23 = "Male living alone"
#     var24 = "Female living alone"
#
# class Relationship_65_Table:
#     table_name = "Relationship by Household Type (including living alone) for the population 65 years and over"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total Population in 65 years and over"
#     var2 = "In households"
#     var3 = "In group quarters"
#     var4 = "Householder"
#     var5 = "Male householder (in family and nonfamily households)"
#     var6 = "Female householder (in family and nonfamily households)"
#     var7 = "In Households"
#     var8 = "Householder"
#     var9 = "Spouse"
#     var10 = "Parent"
#     var11 = "Parent-in-law"
#     var12 = "Other relatives"
#     var13 = "Other nonrelatives"
#     var14 = "In Households"
#     var15 = "Male living alone"
#     var16 = "Female living alone"
#
# class Sex_Marital_Status_Table:
#     table_name = "Sex by Marital Status for the Population 15 years and over"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total Population 15 years and over"
#     var2 = "Never married"
#     var3 = "Now married"
#     var4 = "Separated but still married"
#     var5 = "Divorced"
#     var6 = "Widowed"
#     var7 = "Now married"
#     var8 = "Married, spouse present"
#     var9 = "Married, spouse absent"
#
# class Household_Language_Limited_Table:
#     table_name = "Household Language by Household Limited English Speaking Status"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total Households"
#     var2 = "English only"
#     var3 = "Spanish"
#     var4 = "Indo-European languages"
#     var5 = "Asian and Pacific Island languages"
#     var6 = "Other Languages"
#     var7 = "Spanish"
#     var8 = "Limited English speaking household"
#     var9 = "Not a limited English speaking household"
#     var10 = "Indo-European languages"
#     var11 = "Limited English speaking household"
#     var12 = "Not a limited English speaking household"
#     var13 = "Asian and Pacific Island languages"
#     var14 = "Limited English speaking household"
#     var15 = "Not a limited English speaking household"
#     var16 = "Other languages"
#     var17 = "Limited English speaking household"
#     var18 = "Not a limited English speaking household"
#     var19 = "Total Households"
#     var20 = "Limited english speaking"
#     var21 = "Not limited English speaking"
#
# class Sex_Age_Veteran_Table:
#     table_name = "Sex by Age by Veteran Status for the Civilian Population 18 years and over"
#     Id = "Id"
#     data_types_all = "int"
#     var1 = "Total Civilian Population 18 Years and over"
#     var2 = "Veteram"
#     var3 = "Nonveteran"
